// Fictional characters library
const characters = [
  'Superman',
  'Batman',
  'Wonder Woman',
  'Spider-Man',
  'Iron Man',
  'Captain America',
  'Thor',
  'Black Widow',
  'Hulk',
  'Wolverine',
  'Black Panther',
  'Captain Marvel',
  'Doctor Strange',
  'The Flash',
  'Green Lantern',
  'Aquaman',
  'Cyborg',
  'Shazam',
  'Nightwing',
  'Robin',
  'Batgirl',
  'Batwoman',
  'Catwoman',
  'Supergirl',
  'Gandalf',
  'Aragorn',
  'Frodo',
  'Legolas',
  'Hermione',
  'Harry Potter',
  'Dumbledore',
  'Luke Skywalker',
  'Princess Leia',
  'Han Solo',
  'Chewbacca',
  'Yoda',
  'Darth Vader',
  'Grogu',
  'Boba Fett',
  'Kylo Ren',
  'Rey',
  'Finn',
  'Poe Dameron',
  'R2-D2',
  'C-3PO',
  'BB-8',
  'Jyn Erso',
  'K-2SO',
  'Sherlock Holmes',
  'James Bond',
  'Ethan Hunt',
  'Indiana Jones',
  'Lara Croft',
  'Master Chief',
  'Link',
  'Mario',
  'Luigi',
  'King Koopa',
  'Toad',
  'Pikachu',
  'Naruto',
  'Goku',
  'Neo',
  'Trinity',
  'John Wick',
  'Bilbo Baggins',
  'Gimli'
];

// Places library
const places = [
  'Den',
  'Cave',
  'Fortress',
  'Tower',
  'Castle',
  'Sanctuary',
  'Hideout',
  'Lair',
  'Stronghold',
  'Citadel',
  'Palace',
  'Temple',
  'Shrine',
  'Grotto',
  'Chamber',
  'Hall',
  'Keep',
  'Bastion',
  'Refuge',
  'Retreat',
  'Outpost',
  'Base',
  'Headquarters',
  'Command Center',
  'Observatory',
  'Library',
  'Workshop',
  'Laboratory',
  'Vault',
  'Archive',
  'Gold Mine'
];

/**
 * Generates a random session name by combining a fictional character and a place
 * @returns {string} A randomly generated session name (e.g., "Superman's Den")
 */
export function generateSessionName() {
  const character = characters[Math.floor(Math.random() * characters.length)];
  const place = places[Math.floor(Math.random() * places.length)];
  return `${character}'s ${place}`;
}

